title: larmkx.com
description: My personal site and blog
baseurl: ""
url: "https://larmkx.com"
theme: minima

collections:
  projects:
    output: true
    permalink: /projects/:name/

markdown: redcarpet
future: true
highlighter: none
